sl_user:
    resource: "@SLUserBundle/Resources/config/routing.yml"
    prefix:   /
#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
    
git_hub_comment:
    resource: "@GitHubCommentBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: SLUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout