SLUserBundle\Entity\Security\Login:
    type: entity
    table: null
    repositoryClass: SLUserBundle\Repository\Security\LoginRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
            unique: true
        password:
            type: string
            length: 255
    lifecycleCallbacks: {  }
